spring:
  #redis的配置文件
  redis:
    database: 1  # Redis数据库索引（默认为0）
    host: 47.102.202.189 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: -1  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8    # 连接池中的最大空闲连接 默认 8
        min-idle: 0    # 连接池中的最小空闲连接 默认 0
  #文件上传的最大值以及request请求的最大值
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
      enabled: true
  #mysql的驱动配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nursing-home
    username: root
    password: 12345678
  #jpa的配置文件
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
#端口号
server:
  port: 9000
token:
  # 令牌有效期（默认120分钟）
  expireTime: 12000
user:
  #哪个值的时候是admin用户
  adminUser: 1
  ip: "localhost"
  nodeIp: 80
  #扫码二维码的前端页面
  codePath: "/generateCodevVisitors"


